# Generated by Django 5.1 on 2024-08-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createevent',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
