# Generated by Django 5.1 on 2024-09-12 03:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_event', '0002_alter_createevent_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='createevent',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
