# Generated by Django 5.0.3 on 2024-09-09 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myevents',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
